export const SIDEBAR = [
  {
    icon: 'HomeIcon',
    name: 'Home',
    link: '/'
  },
  {
    icon: 'CalendarIcon',
    name: 'Calendar',
    link: '/calendar'
  },
  {
    icon: 'TaskIcon',
    name: 'Task',
    link: '/task'
  },
  {
    icon: 'EvaluationIcon',
    name: 'Evaluation',
    link: '/evaluation'
  },
  {
    icon: 'TreeIcon',
    name: 'Tree',
    link: '/tree'
  },
  {
    icon: 'SettingIcon',
    name: 'Setting',
    link: '/setting'
  },
]

export const TASKS = {
  1: [
    {
      name: "UIUX",
      status: "2",
      date: "May 17",
      time: " 7:30 - 9:30 AM",
      place: "D9-401",
      number_file: 3,
    },
    {
      name: "Học ngữ pháp N2",
      status: "2",
      date: "May 15",
      time: " 8:30 - 9:30 AM",
      place: "Home",
      number_file: 2,
    },
    {
      name: "Học từ vựng N2",
      status: "2",
      date: "May 15",
      time: " 7:30 - 8:30 AM",
      place: "Home",
      number_file: 2,
    },
    {
      name: "BTVN 3/5",
      status: "2",
      date: "May 15",
      time: "1:30 - 2:30 PM",
      place: "Home",
      number_file: 3,
    },
    {
      name: "BTVN 2/5",
      status: "2",
      date: "May 14",
      time: " 7:30 - 9:30 AM",
      place: "Home",
      number_file: 3,
    },
    {
      name: "BTVN 2/5",
      status: "2",
      date: "May 14",
      time: " 7:30 - 9:30 AM",
      place: "Home",
      number_file: 3,
    }
  ],
  2: [
    {
      name: "Project Planning",
      status: "1",
      date: "May 18",
      time: " 10:00 - 11:00 AM",
      place: "Room",
      number_file: 2,
    },
    {
      name: "BTVN 4/5",
      status: "2",
      date: "May 16",
      time: " 7:30 - 9:30 AM",
      place: "Home",
      number_file: 3,
    },
    {
      name: "BTVN 5/5",
      status: "2",
      date: "May 17",
      time: " 7:30 - 9:30 AM",
      place: "Home",
      number_file: 3,
    },
    {
      name: "Review Meeting",
      status: "1",
      date: "May 19",
      time: " 9:00 - 10:00 AM",
      place: "D9-401",
      number_file: 4,
    },
    {
      name: "Training Session",
      status: "1",
      date: "May 20",
      time: " 2:00 - 4:00 PM",
      place: "Room",
      number_file: 1,
    },
    {
      name: "Code Refactoring",
      status: "2",
      date: "May 21",
      time: " 10:00 - 11:00 AM",
      place: "Office",
      number_file: 2,
    }
  ],
  3: [
    {
      name: "Project Presentation",
      status: "1",
      date: "May 18",
      time: " 9:00 - 11:00 AM",
      place: "D9-401",
      number_file: 5,
    },
    {
      name: "BTVN 6/5",
      status: "2",
      date: "May 18",
      time: " 7:30 - 9:30 AM",
      place: "Home",
      number_file: 3,
    },
    {
      name: "User Testing",
      status: "1",
      date: "May 22",
      time: " 2:00 - 4:00 PM",
      place: "Testing Lab",
      number_file: 3,
    },
    {
      name: "Client Meeting",
      status: "1",
      date: "May 23",
      time: " 11:00 AM - 12:00 PM",
      place: "Office",
      number_file: 2,
    },
    {
      name: "Report Compilation",
      status: "2",
      date: "May 24",
      time: " 3:00 - 5:00 PM",
      place: "Office",
      number_file: 1,
    },
    {
      name: "Performance Evaluation",
      status: "1",
      date: "May 25",
      time: " 10:00 - 11:00 AM",
      place: "Cabin",
      number_file: 2,
    }
  ], 4: [
    {
      name: "Data Analysis",
      status: "1",
      date: "May 26",
      time: " 10:00 - 11:00 AM",
      place: "Data Lab",
      number_file: 3,
    },
    {
      name: "Marketing Campaign",
      status: "2",
      date: "May 27",
      time: " 2:00 - 4:00 PM",
      place: "Office",
      number_file: 2,
    },
    {
      name: "Budget Planning",
      status: "1",
      date: "May 28",
      time: " 9:00 - 10:00 AM",
      place: "Room",
      number_file: 4,
    },
    {
      name: "Product Development",
      status: "2",
      date: "May 29",
      time: " 10:00 - 12:00 PM",
      place: "Lab",
      number_file: 5,
    },
    {
      name: "Financial Report",
      status: "1",
      date: "May 30",
      time: " 11:00 AM - 12:00 PM",
      place: "Office",
      number_file: 1,
    },
    {
      name: "Employee Training",
      status: "2",
      date: "May 31",
      time: " 9:00 - 11:00 AM",
      place: "Room",
      number_file: 2,
    }
  ], 5: [
    {
      name: "Content Creation",
      status: "1",
      date: "June 1",
      time: " 2:00 - 4:00 PM",
      place: "Office",
      number_file: 3,
    },
    {
      name: "Customer Support",
      status: "2",
      date: "June 2",
      time: " 10:00 - 12:00 PM",
      place: "Center",
      number_file: 2,
    },
    {
      name: "Inventory Management",
      status: "1",
      date: "June 3",
      time: " 9:00 - 10:00 AM",
      place: "Warehouse",
      number_file: 4,
    },
    {
      name: "Social Media Marketing",
      status: "2",
      date: "June 4",
      time: " 11:00 AM - 12:00 PM",
      place: "Office",
      number_file: 5,
    },
    {
      name: "Website Maintenance",
      status: "1",
      date: "June 5",
      time: " 9:00 - 11:00 AM",
      place: "IT Department",
      number_file: 1,
    },
    {
      name: "Team Meeting",
      status: "2",
      date: "June 6",
      time: " 2:00 - 4:00 PM",
      place: "Room",
      number_file: 2,
    }
  ],
  6: [
    {
      name: "Market Research",
      status: "1",
      date: "June 7",
      time: " 10:00 - 11:00 AM",
      place: "Lab",
      number_file: 3,
    },
    {
      name: "Project Management",
      status: "2",
      date: "June 8",
      time: " 2:00 - 4:00 PM",
      place: "Office",
      number_file: 2,
    },
    {
      name: "Client Presentation",
      status: "1",
      date: "June 9",
      time: " 9:00 - 10:00 AM",
      place: "Office",
      number_file: 4,
    },
    {
      name: "Quality Assurance",
      status: "2",
      date: "June 10",
      time: " 10:00 AM - 12:00 PM",
      place: "Coffe",
      number_file: 5,
    },
    {
      name: "Staff Training",
      status: "1",
      date: "June 11",
      time: " 11:00 AM - 12:00 PM",
      place: "Room",
      number_file: 1,
    },
    {
      name: "Product Launch",
      status: "2",
      date: "June 12",
      time: " 2:00 - 4:00 PM",
      place: "Hall",
      number_file: 2,
    }
  ],
};
